baseURL = ""
languageCode = "en-us"
title = "Aerele Technologies"
themesDir = "themes"
theme = "hugo-serif-theme"
publishDir = "docs"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = "UA-148400227-1"
  google_tag_manager_id = ""

  [params.logo]
    alt = "Aerele Technologies"

  [params.homepage_meta_tags]
    meta_description = "Aerele Technologies is a software development company in Tiruppur, India. It helps business leaders to take their business to next steps. DevOps, CI//CD, ERP, Custom Software Development are the verticles that it concentartes."
    meta_og_title = "Aerele Technologies"
    meta_og_type = "website"
    meta_og_url = "https://aerele.in"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "Aerele Technologies is a software development company in Tiruppur, India. It helps business leaders to take their business to next steps. DevOps, CI//CD, ERP, Custom Software Development are the verticles that it concentartes."

[menu]
  # Main Menu
  [[menu.main]]
    name = "Services"
    url = "/services/"
      weight = 1


#  [[menu.main]]
#      name = "Team"
#      url = "/team/"
#      weight = 2 

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2
